import { FailureCode, FailureStateDefinition } from "@/types/verification";

export const FAILURE_REGISTRY: Record<FailureCode, FailureStateDefinition> = {
  // Session Failures
  SESSION_NOT_FOUND: {
    code: 'SESSION_NOT_FOUND',
    category: 'SESSION',
    userMessage: 'Attendance session not found.',
    retryable: false,
    securitySensitive: false,
    severity: 'MEDIUM',
    outcome: 'REJECTED',
  },
  SESSION_EXPIRED: {
    code: 'SESSION_EXPIRED',
    category: 'SESSION',
    userMessage: 'This attendance session has ended.',
    retryable: false,
    securitySensitive: false,
    severity: 'LOW',
    outcome: 'REJECTED',
  },
  SESSION_NOT_OPEN: {
    code: 'SESSION_NOT_OPEN',
    category: 'SESSION',
    userMessage: 'The attendance window is not currently open.',
    retryable: false,
    securitySensitive: false,
    severity: 'LOW',
    outcome: 'REJECTED',
  },
  STUDENT_NOT_ENROLLED: {
    code: 'STUDENT_NOT_ENROLLED',
    category: 'SESSION',
    userMessage: 'You are not enrolled in this course session.',
    retryable: false,
    securitySensitive: false,
    severity: 'MEDIUM',
    outcome: 'REJECTED',
  },
  SESSION_ALREADY_COMPLETED: {
    code: 'SESSION_ALREADY_COMPLETED',
    category: 'SESSION',
    userMessage: 'This session has already been finalized by the teacher.',
    retryable: false,
    securitySensitive: false,
    severity: 'LOW',
    outcome: 'REJECTED',
  },
  ATTENDANCE_ALREADY_RECORDED: {
    code: 'ATTENDANCE_ALREADY_RECORDED',
    category: 'SESSION',
    userMessage: 'Your attendance is already successfully recorded.',
    retryable: false,
    securitySensitive: false,
    severity: 'LOW',
    outcome: 'ACCEPTED',
  },

  // Proximity Failures
  PROXIMITY_UNAVAILABLE: {
    code: 'PROXIMITY_UNAVAILABLE',
    category: 'PROXIMITY',
    userMessage: 'Proximity detection hardware is not available on this device.',
    retryable: true,
    securitySensitive: false,
    severity: 'MEDIUM',
    outcome: 'SYSTEM_ERROR',
  },
  PROXIMITY_PERMISSION_DENIED: {
    code: 'PROXIMITY_PERMISSION_DENIED',
    category: 'PROXIMITY',
    userMessage: 'Microphone permission is required to detect the classroom beacon.',
    retryable: true,
    securitySensitive: false,
    severity: 'LOW',
    outcome: 'RETRY_REQUIRED',
  },
  PROXIMITY_TIMEOUT: {
    code: 'PROXIMITY_TIMEOUT',
    category: 'PROXIMITY',
    userMessage: 'Classroom signal not detected. Ensure you are inside the classroom.',
    retryable: true,
    securitySensitive: false,
    severity: 'LOW',
    outcome: 'RETRY_REQUIRED',
  },
  PROXIMITY_SIGNAL_NOT_DETECTED: {
    code: 'PROXIMITY_SIGNAL_NOT_DETECTED',
    category: 'PROXIMITY',
    userMessage: 'No active classroom beacon heard. Hold your phone steady.',
    retryable: true,
    securitySensitive: false,
    severity: 'LOW',
    outcome: 'RETRY_REQUIRED',
  },
  PROXIMITY_SIGNAL_INVALID: {
    code: 'PROXIMITY_SIGNAL_INVALID',
    category: 'PROXIMITY',
    userMessage: 'Received acoustic signal does not match the active session.',
    retryable: true,
    securitySensitive: false,
    severity: 'MEDIUM',
    outcome: 'REJECTED',
  },
  PROXIMITY_CHALLENGE_EXPIRED: {
    code: 'PROXIMITY_CHALLENGE_EXPIRED',
    category: 'PROXIMITY',
    userMessage: 'Classroom beacon challenge expired. Refreshing token...',
    retryable: true,
    securitySensitive: false,
    severity: 'LOW',
    outcome: 'RETRY_REQUIRED',
  },
  PROXIMITY_CHALLENGE_REPLAYED: {
    code: 'PROXIMITY_CHALLENGE_REPLAYED',
    category: 'PROXIMITY',
    userMessage: 'Verification could not be completed.',
    retryable: false,
    securitySensitive: true,
    severity: 'HIGH',
    outcome: 'BLOCKED',
  },
  PROXIMITY_VERIFICATION_FAILED: {
    code: 'PROXIMITY_VERIFICATION_FAILED',
    category: 'PROXIMITY',
    userMessage: 'Could not verify classroom proximity evidence.',
    retryable: true,
    securitySensitive: false,
    severity: 'MEDIUM',
    outcome: 'REJECTED',
  },
  PROXIMITY_CONFLICT: {
    code: 'PROXIMITY_CONFLICT',
    category: 'PROXIMITY',
    userMessage: 'Conflicting location signals detected. Please retry.',
    retryable: true,
    securitySensitive: false,
    severity: 'MEDIUM',
    outcome: 'REJECTED',
  },

  // Camera Failures
  CAMERA_UNAVAILABLE: {
    code: 'CAMERA_UNAVAILABLE',
    category: 'CAMERA',
    userMessage: 'No usable camera detected on this device.',
    retryable: false,
    securitySensitive: false,
    severity: 'HIGH',
    outcome: 'SYSTEM_ERROR',
  },
  CAMERA_PERMISSION_DENIED: {
    code: 'CAMERA_PERMISSION_DENIED',
    category: 'CAMERA',
    userMessage: 'Please allow camera access in browser settings to verify identity.',
    retryable: true,
    securitySensitive: false,
    severity: 'LOW',
    outcome: 'RETRY_REQUIRED',
  },
  CAMERA_PERMISSION_BLOCKED: {
    code: 'CAMERA_PERMISSION_BLOCKED',
    category: 'CAMERA',
    userMessage: 'Camera access is permanently blocked in browser permissions.',
    retryable: false,
    securitySensitive: false,
    severity: 'HIGH',
    outcome: 'REJECTED',
  },
  CAMERA_INITIALIZATION_FAILED: {
    code: 'CAMERA_INITIALIZATION_FAILED',
    category: 'CAMERA',
    userMessage: 'Unable to start camera stream. Restart browser tab.',
    retryable: true,
    securitySensitive: false,
    severity: 'MEDIUM',
    outcome: 'SYSTEM_ERROR',
  },
  CAMERA_INTERRUPTED: {
    code: 'CAMERA_INTERRUPTED',
    category: 'CAMERA',
    userMessage: 'Camera stream was interrupted by another application.',
    retryable: true,
    securitySensitive: false,
    severity: 'LOW',
    outcome: 'RETRY_REQUIRED',
  },
  CAMERA_TIMEOUT: {
    code: 'CAMERA_TIMEOUT',
    category: 'CAMERA',
    userMessage: 'Camera frame acquisition timed out. Please try again.',
    retryable: true,
    securitySensitive: false,
    severity: 'LOW',
    outcome: 'RETRY_REQUIRED',
  },

  // Face Detection Failures
  FACE_NOT_DETECTED: {
    code: 'FACE_NOT_DETECTED',
    category: 'FACE_DETECTION',
    userMessage: 'No face detected. Center your face inside the guide frame.',
    retryable: true,
    securitySensitive: false,
    severity: 'LOW',
    outcome: 'RETRY_REQUIRED',
  },
  MULTIPLE_FACES_DETECTED: {
    code: 'MULTIPLE_FACES_DETECTED',
    category: 'FACE_DETECTION',
    userMessage: 'Multiple faces detected. Ensure only you are visible.',
    retryable: true,
    securitySensitive: false,
    severity: 'LOW',
    outcome: 'RETRY_REQUIRED',
  },
  FACE_TOO_SMALL: {
    code: 'FACE_TOO_SMALL',
    category: 'FACE_DETECTION',
    userMessage: 'Move closer to the camera to fill the frame.',
    retryable: true,
    securitySensitive: false,
    severity: 'LOW',
    outcome: 'RETRY_REQUIRED',
  },
  FACE_OUT_OF_FRAME: {
    code: 'FACE_OUT_OF_FRAME',
    category: 'FACE_DETECTION',
    userMessage: 'Position your face entirely within the oval guide.',
    retryable: true,
    securitySensitive: false,
    severity: 'LOW',
    outcome: 'RETRY_REQUIRED',
  },
  FACE_POOR_QUALITY: {
    code: 'FACE_POOR_QUALITY',
    category: 'FACE_DETECTION',
    userMessage: 'Lighting is too dim or blurry. Move to a brighter area.',
    retryable: true,
    securitySensitive: false,
    severity: 'LOW',
    outcome: 'RETRY_REQUIRED',
  },
  FACE_POOR_POSE: {
    code: 'FACE_POOR_POSE',
    category: 'FACE_DETECTION',
    userMessage: 'Look straight at the camera without tilting.',
    retryable: true,
    securitySensitive: false,
    severity: 'LOW',
    outcome: 'RETRY_REQUIRED',
  },
  FACE_OCCLUDED: {
    code: 'FACE_OCCLUDED',
    category: 'FACE_DETECTION',
    userMessage: 'Face is partially covered. Remove hand or obstruction.',
    retryable: true,
    securitySensitive: false,
    severity: 'LOW',
    outcome: 'RETRY_REQUIRED',
  },

  // Face Identity Failures
  FACE_NOT_ENROLLED: {
    code: 'FACE_NOT_ENROLLED',
    category: 'FACE_IDENTITY',
    userMessage: 'No biometric profile found. Complete enrollment first.',
    retryable: false,
    securitySensitive: false,
    severity: 'HIGH',
    outcome: 'REJECTED',
  },
  FACE_MISMATCH: {
    code: 'FACE_MISMATCH',
    category: 'FACE_IDENTITY',
    userMessage: 'Biometric verification did not match enrolled profile.',
    retryable: true,
    securitySensitive: false,
    severity: 'HIGH',
    outcome: 'REJECTED',
  },
  FACE_CONFIDENCE_INSUFFICIENT: {
    code: 'FACE_CONFIDENCE_INSUFFICIENT',
    category: 'FACE_IDENTITY',
    userMessage: 'Match confidence below threshold. Retrying under better lighting.',
    retryable: true,
    securitySensitive: false,
    severity: 'MEDIUM',
    outcome: 'RETRY_REQUIRED',
  },
  FACE_VERIFICATION_ERROR: {
    code: 'FACE_VERIFICATION_ERROR',
    category: 'FACE_IDENTITY',
    userMessage: 'Biometric comparison engine encountered an unexpected error.',
    retryable: true,
    securitySensitive: false,
    severity: 'HIGH',
    outcome: 'SYSTEM_ERROR',
  },

  // Liveness Failures
  LIVENESS_UNAVAILABLE: {
    code: 'LIVENESS_UNAVAILABLE',
    category: 'LIVENESS',
    userMessage: 'Anti-spoofing engine unavailable on this browser.',
    retryable: true,
    securitySensitive: false,
    severity: 'HIGH',
    outcome: 'SYSTEM_ERROR',
  },
  LIVENESS_TIMEOUT: {
    code: 'LIVENESS_TIMEOUT',
    category: 'LIVENESS',
    userMessage: 'Liveness evaluation timed out. Follow the on-screen prompt.',
    retryable: true,
    securitySensitive: false,
    severity: 'LOW',
    outcome: 'RETRY_REQUIRED',
  },
  LIVENESS_FAILED: {
    code: 'LIVENESS_FAILED',
    category: 'LIVENESS',
    userMessage: 'Liveness could not be verified. Please retry.',
    retryable: true,
    securitySensitive: false,
    severity: 'MEDIUM',
    outcome: 'REJECTED',
  },
  POSSIBLE_PRESENTATION_ATTACK: {
    code: 'POSSIBLE_PRESENTATION_ATTACK',
    category: 'LIVENESS',
    userMessage: 'Verification could not be completed.',
    retryable: false,
    securitySensitive: true,
    severity: 'CRITICAL',
    outcome: 'BLOCKED',
  },

  // Auth / Device Failures
  STUDENT_NOT_AUTHENTICATED: {
    code: 'STUDENT_NOT_AUTHENTICATED',
    category: 'AUTHENTICATION',
    userMessage: 'Session expired. Please log in again.',
    retryable: false,
    securitySensitive: false,
    severity: 'MEDIUM',
    outcome: 'REJECTED',
  },
  DEVICE_NOT_REGISTERED: {
    code: 'DEVICE_NOT_REGISTERED',
    category: 'AUTHENTICATION',
    userMessage: 'This device is not registered to your student account.',
    retryable: false,
    securitySensitive: false,
    severity: 'HIGH',
    outcome: 'REJECTED',
  },
  DEVICE_IDENTITY_MISMATCH: {
    code: 'DEVICE_IDENTITY_MISMATCH',
    category: 'AUTHENTICATION',
    userMessage: 'Verification could not be completed.',
    retryable: false,
    securitySensitive: true,
    severity: 'CRITICAL',
    outcome: 'BLOCKED',
  },
  AUTHENTICATION_EXPIRED: {
    code: 'AUTHENTICATION_EXPIRED',
    category: 'AUTHENTICATION',
    userMessage: 'Your login credentials have expired. Please re-authenticate.',
    retryable: true,
    securitySensitive: false,
    severity: 'LOW',
    outcome: 'RETRY_REQUIRED',
  },
  AUTHORIZATION_FAILED: {
    code: 'AUTHORIZATION_FAILED',
    category: 'AUTHENTICATION',
    userMessage: 'Unauthorized access to this session.',
    retryable: false,
    securitySensitive: false,
    severity: 'HIGH',
    outcome: 'REJECTED',
  },

  // Security Failures
  INVALID_REQUEST: {
    code: 'INVALID_REQUEST',
    category: 'SECURITY',
    userMessage: 'Malformed verification submission.',
    retryable: false,
    securitySensitive: false,
    severity: 'MEDIUM',
    outcome: 'REJECTED',
  },
  INVALID_SIGNATURE: {
    code: 'INVALID_SIGNATURE',
    category: 'SECURITY',
    userMessage: 'Verification could not be completed.',
    retryable: false,
    securitySensitive: true,
    severity: 'CRITICAL',
    outcome: 'BLOCKED',
  },
  NONCE_INVALID: {
    code: 'NONCE_INVALID',
    category: 'SECURITY',
    userMessage: 'Security challenge was invalid. Re-attempting...',
    retryable: true,
    securitySensitive: false,
    severity: 'MEDIUM',
    outcome: 'REJECTED',
  },
  TIMESTAMP_INVALID: {
    code: 'TIMESTAMP_INVALID',
    category: 'SECURITY',
    userMessage: 'Submission timestamp outside acceptable window. Retrying...',
    retryable: true,
    securitySensitive: false,
    severity: 'LOW',
    outcome: 'RETRY_REQUIRED',
  },
  REPLAY_DETECTED: {
    code: 'REPLAY_DETECTED',
    category: 'SECURITY',
    userMessage: 'Verification could not be completed.',
    retryable: false,
    securitySensitive: true,
    severity: 'CRITICAL',
    outcome: 'BLOCKED',
  },
  RATE_LIMITED: {
    code: 'RATE_LIMITED',
    category: 'SECURITY',
    userMessage: 'Too many attempts. Please wait a moment before trying again.',
    retryable: false,
    securitySensitive: true,
    severity: 'HIGH',
    outcome: 'BLOCKED',
  },
  SUSPICIOUS_ACTIVITY: {
    code: 'SUSPICIOUS_ACTIVITY',
    category: 'SECURITY',
    userMessage: 'Verification could not be completed.',
    retryable: false,
    securitySensitive: true,
    severity: 'CRITICAL',
    outcome: 'BLOCKED',
  },

  // System Failures
  NETWORK_UNAVAILABLE: {
    code: 'NETWORK_UNAVAILABLE',
    category: 'SYSTEM',
    userMessage: 'Offline: verification queued for background sync.',
    retryable: true,
    securitySensitive: false,
    severity: 'LOW',
    outcome: 'SYSTEM_ERROR',
  },
  SERVER_UNAVAILABLE: {
    code: 'SERVER_UNAVAILABLE',
    category: 'SYSTEM',
    userMessage: 'Verification service temporarily unreachable.',
    retryable: true,
    securitySensitive: false,
    severity: 'HIGH',
    outcome: 'SYSTEM_ERROR',
  },
  VERIFICATION_SERVICE_ERROR: {
    code: 'VERIFICATION_SERVICE_ERROR',
    category: 'SYSTEM',
    userMessage: 'Verification service encountered an issue.',
    retryable: true,
    securitySensitive: false,
    severity: 'HIGH',
    outcome: 'SYSTEM_ERROR',
  },
  DATABASE_ERROR: {
    code: 'DATABASE_ERROR',
    category: 'SYSTEM',
    userMessage: 'Database connection issue. Retrying transaction...',
    retryable: true,
    securitySensitive: false,
    severity: 'CRITICAL',
    outcome: 'SYSTEM_ERROR',
  },
  INTERNAL_ERROR: {
    code: 'INTERNAL_ERROR',
    category: 'SYSTEM',
    userMessage: 'An unexpected system error occurred.',
    retryable: true,
    securitySensitive: false,
    severity: 'CRITICAL',
    outcome: 'SYSTEM_ERROR',
  },
};

export function getFailureDefinition(code: FailureCode): FailureStateDefinition {
  return (
    FAILURE_REGISTRY[code] || {
      code,
      category: 'SYSTEM',
      userMessage: 'An unexpected error occurred.',
      retryable: true,
      securitySensitive: false,
      severity: 'HIGH',
      outcome: 'SYSTEM_ERROR',
    }
  );
}
